### ISSUE TITLE
Python3 porting

### ISSUE THREAD

**Issue by DarkRedman** [closeio/Flask-gzip#11]
I ported 
`import StringIO` to `from io import StringIO`
I got an error `TypeError: string argument expected, got 'bytes'`

`File "/usr/lib/python3.4/gzip.py", line 252, in _write_gzip_header
self.fileobj.write(b'\037\213')             # magic header`

I don't know how to fix this part.

**Comment by delliriun** [comment]
As this project seems to be dead. I recommend using the **flask-compress** instead.

**Comment by tsx** [comment]
Release 0.2 is now python3-compatible.
