### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by DachuanZhao** [closeio/Flask-gzip#18]
the error is "ModuleNotFoundError: No module named 'flask.ext'"
my python version is 3.7 and my flask version is 1.0.2

**Comment by wojcikstefan** [comment]
Hey @DachuanZhao, I updated the setup instructions in 7198fd6. Does it work for you now?

**Comment by dimitri-1105** [comment]
line 20, in <module>
    from flask.ext.uploads import UploadSet,IMAGES
ModuleNotFoundError: No module named 'flask.ext'
